server:
  port: 2333
  address: 0.0.0.0

lavalink:
  server:
    password: "supersecret"
    sources:
      youtube: true
      soundcloud: true
      bandcamp: true
      twitch: true
      http: true
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    playerUpdateInterval: 5

metrics:
  prometheus:
    enabled: false

logging:
  level:
    root: INFO
    lavalink: INFO
