server:
  port: 2333

lavalink:
  server:
    password: "supersecret"
    sources:
      youtube: true
      soundcloud: true
      bandcamp: true
      twitch: true
      http: true

metrics:
  prometheus:
    enabled: false
