server:
  port: ${PORT:2333}
  address: 0.0.0.0

lavalink:
  server:
    password: "supersecret"
    sources:
      youtube: true
      soundcloud: true
      bandcamp: true
      twitch: true
      http: true

logging:
  level:
    root: INFO
    lavalink: INFO
